version: "3.2"

services:
  frontend:
    build:
      context: ../.
      dockerfile: frontend/Dockerfile.dev
    image: web3-frontend
    environment:
      - NODE_ENV=development
      - REACT_APP_NODE_URL=${NODE_URL}
      - REACT_APP_NETWORK_NAME=${NETWORK_NAME}
    restart: on-failure
    volumes:
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones
      - ./../frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - api

  server:
    image: nginx
    environment:
      - NGINX_NODE_RPC=${NODE_URL}
    volumes:
    - ./../server/templates:/etc/nginx/templates
    - ./../server/nginx.conf:/etc/nginx/nginx.conf
    - ./../server/includes:/etc/nginx/my-includes
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - frontend
